### ISSUE TITLE
Roadmap / Wishlist

### ISSUE THREAD

**Issue by dotfloat** [svkaiser/Doom64EX#74]
# Roadmap for Doom64EX-next

This is a list of stuff that needs to be done to be able to have a proper release.

**†** In progress
**!** Critical
**?** Optional

### Doom 64 ROM without Wadgen
- [x] Rewrite deflate code **!**
- [x] WAD loading **!**
- [x] N64 graphics format **!**
- [x] N64 MIDI tracks **!**
- [ ] N64 MIDI soundfont **!**
- [ ] WAD,SSEQ,SN64 offsets for all ROM versions  **!**
- [ ] File select dialog when game data is missing **!**

### Console
- [ ] Centralised logging API **!**
- [ ] Colour console text **?**
- [ ] Auto-complete dropdown
- [ ] GNU readline support **?**
- [ ] Fix incorrect tokenisation of semi-colons inside double-quotes **!**

### Menu
- [ ] Normalise font size
- [ ] Clean up and rename settings menus
- [ ] Use hardware cursor when possible
- [ ] Allow typing in password menu

### Input
- [ ] SDL_GameController
- [ ] New API that supports multiple controllers, players and bindings
- [ ] Support N64 controllers with original bindings **?**

### Multiplayer
- [ ] Split-screen **?**

### Modding support / Cleanup
- [ ] Basic DECORATE support
- [ ] Remove the need for `LumpHash`
- [ ] Add a menu for selecting PWADs **?**

### Renderer
- [ ] Replace GLAD for the glbinding library
- [ ] Isolate GL 1.4 code **?**
- [ ] Experimental GL 3.3 **?**

### Core
- [ ] Replace C miniloops with C++ class equivalents
- [ ] Isolate network code

### General
- [ ] Publish dependencies in an archive
- [ ] Flatpak (Linux)
- [ ] Figure out macOS distribution
